# Generated by Django 3.1.2 on 2020-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecat', models.CharField(max_length=200, unique=True)),
                ('partnumber', models.CharField(max_length=200, unique=True)),
                ('productname', models.CharField(max_length=200, unique=True)),
                ('product_price', models.IntegerField()),
                ('detail', models.CharField(max_length=200, unique=True)),
                ('longdesc', models.TextField(max_length=200, unique=True)),
                ('link', models.URLField()),
                ('img', models.URLField()),
            ],
        ),
    ]
