# Generated by Django 3.1.2 on 2020-10-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='longdesc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='namecat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=200),
        ),
    ]
